name: Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
permissions:
  id-token: write # Required for PyPI OIDC
jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/beautysh
    steps:
      - uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: "*.{whl,tar.gz}"
          out-file-path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
