name: Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
permissions:
  id-token: write # Required for PyPI OIDC
jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/beautysh
    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: "*.whl"
          out-file-path: dist
      - name: Download release assets (tar.gz)
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: "*.tar.gz"
          out-file-path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
